DS.WEB/Componentes/ViewComponent/Grid/GridViewComponent.cs
namespace DS.WEB.Componentes.ViewComponent.Grid;

using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Text.Json;

public class GridViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(dynamic options)
    {
        GridOptions gridOptions = options["options"].Field;

        ViewData["id"] = !string.IsNullOrEmpty(gridOptions.Id) ? gridOptions.Id : gridOptions.GetElementId;
        ViewData["name"] = gridOptions.AspFor;
        ViewData["columnsParams"] = JsonSerializer.Serialize(gridOptions.Colunas);
        ViewData["acoes"] = JsonSerializer.Serialize(gridOptions.Acoes);
        ViewData["ordenacaoPadraoCrescente"] = gridOptions.OrdenacaoPadraoCrescente;
        ViewData["ordenacaoPadrao"] = JsonSerializer.Serialize(gridOptions.OrdenacaoPadrao);
        ViewData["permiteUnicaSelecao"] = gridOptions.PermiteUnicaSelecao;
        ViewData["permiteMultiplaSelecao"] = gridOptions.PermiteMultiplaSelecao;
        ViewData["permiteMultiplaExclusao"] = gridOptions.PermiteMultiplaExclusao;
        ViewData["permitePesquisa"] = gridOptions.PesquisePor.Any();
        ViewData["pesquisePor"] = gridOptions.PesquisePor.ToArray();

        return View();
    }
}

DS.WEB/Componentes/ViewComponent/Pesquisa/PesquisaViewComponent.cs
namespace DS.WEB.Componentes.ViewComponent.Pesquisa;

using Microsoft.AspNetCore.Mvc;
using DS.WEB.Componentes.Builders;

public class PesquisaViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(PesquisaBuilder options)
    {
        PesquisaOptions pesquisaForOptions = options.Build();

        ViewData["id"] = pesquisaForOptions.GetElementId;
        ViewData["name"] = $"{pesquisaForOptions.AspFor}.{pesquisaForOptions.KeyName}";
        ViewData["label"] = pesquisaForOptions.Label;
        ViewData["Tipo"] = pesquisaForOptions.TipoModel;
        ViewData["Action"] = pesquisaForOptions.Action;
        ViewData["Method"] = pesquisaForOptions.Method;
        ViewData["KeyName"] = pesquisaForOptions.KeyName;
        ViewData["ParametrosPesquisa"] = pesquisaForOptions.ParametrosPesquisa;
        ViewData["EhPesquisaServerSide"] = pesquisaForOptions.EhPesquisaServerSide;
        ViewData["FiltrarPor"] = pesquisaForOptions.FiltrarPor;
        ViewData["AoSelecionar"] = pesquisaForOptions.AoSelecionar;
        ViewData["AoApagar"] = pesquisaForOptions.AoApagar;

        return View();
    }
}

DS.WEB/Pages/Disciplina/AdicionarAlunoDisciplina.cshtml.cs
using DS.WEB.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;

namespace DS.WEB.Pages.Disciplina;

public class AdicionarAlunoDisciplinaModel : PageModel
{
    public List<AlunoModel> AlunosDisciplina { get; }

    public AlunoModel Aluno { get; }

    public IActionResult OnGet(string id, string nome)
    {
        if(!string.IsNullOrEmpty(id) && !string.IsNullOrEmpty(nome))
        {
            ViewData["idDisciplina"] = id;
            ViewData["nomeDisciplina"] = nome;
        }

        return Page();
    }
}

DS.WEB/Pages/Disciplina/AterrissagemDisciplina.cshtml.cs
using DS.WEB.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;

namespace DS.WEB.Pages.Disciplina
{
    public class AterrissagemDisciplinaModel : PageModel
    {
        public List<DisciplinaModel> Disciplinas { get; }

        public void OnGet()
        {
        }
    }
}

DS.WEB/Pages/Disciplina/CadastrarDisciplina.cshtml.cs
using DS.WEB.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DS.WEB.Pages.Disciplina
{
    public class CadastrarDisciplinaModel : PageModel
    {
        public ProfessorModel Professor { get; }

        public void OnGet(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                ViewData["idDisciplina"] = id;
            }
        }
    }
}

DS.WEB/Pages/Disciplina/AdicionarAlunoDisciplina.cshtml
@page
@model DS.WEB.Pages.Disciplina.AdicionarAlunoDisciplinaModel
@{
    Layout = "_LayoutCadastro";
    var idDisciplina = (string)ViewData["idDisciplina"];
    var nomeDisciplina = (string)ViewData["nomeDisciplina"];

    ViewData["tituloFuncao"] = nomeDisciplina ?? "Associação de alunos à disciplina";
}

<div class="row">
    <div class="col-xl-9">
        <vc:pesquisa options="@Html.Pesquisa(m => m.Aluno).Action("http://localhost:5187/Aluno", "GET")"></vc:pesquisa>
    </div>
    <div class="col-xl-3 mt-auto mb-3">
        <button onclick="aoAdicionarAlunoDisciplina(event)" type="button" id="gravar" class="w-100 botao-cadastrar btn btn-success py-2 my-0 px-4">
            <i style="color: white;" class="me-2 fa fa-plus"></i>Adicionar aluno
        </button>
    </div>
</div>

<div class="row">
    <div class="col-xl-12">
        <vc:grid options="@(Html.GridOptions(m => m.AlunosDisciplina)
                                .AddColumn(c => c.Bound(m => m.Matricula).FlexBasis(200))
                                .AddColumn(c => c.Bound(m => m.Nome))
                                .AddAction(a => a.Remover().AoClicar("aoRemoverAlunoDisciplina")))"></vc:grid>
    </div>
</div>

<script defer>
let idDisciplina;
EventDomContentLoaded(async () => {
    const botaoGravar = document.getElementById("gravar");
    botaoGravar.classList.add('d-none');

    const botaoCancelar = document.getElementById("cancelar");
    botaoCancelar.addEventListener('click', (ev) => {
        ev.preventDefault();
        new Modal().confirmacao("Tem certeza que deseja voltar para a lista de disciplinas ?", () => {
            window.location.href = "/Disciplina/Aterrissagem"
        }).render();
    })

    botaoCancelar.classList.value = 'botao-cancelar btn btn-info py-2 my-0 px-4'
    botaoCancelar.innerHTML = "";
    const iconeVoltar = h('i', {'class': 'me-2 fa fa-arrow-left'})
    botaoCancelar.appendChild(iconeVoltar);
    botaoCancelar.innerHTML += "Voltar"

    await pesquiseTodosAlunos();
})

async function pesquiseTodosAlunos() {
    const options = {
        url: `${APIHelper.LocalHost}/Aluno`,
        method: "GET"
    }
    
    const resposta = await postJSON(options);

    if (resposta && resposta.success) {
        await pesquiseAlunosDisciplina(resposta.data);
    }
}

async function pesquiseAlunosDisciplina(todosAlunos) {
    idDisciplina = '@Html.Raw(idDisciplina)';
    const urlDisciplina = `${APIHelper.LocalHostDisciplina}/classes/${idDisciplina}/student-classes`
    
    const options = {
        url: urlDisciplina,
        method: "GET"
    }
    const resposta = await postJSON(options);
    if (resposta && resposta.length) 
    {
        const alunosDisciplina = todosAlunos.filter(aluno => resposta.find(alunoDisciplina => alunoDisciplina.student_id == aluno.id));
        if (alunosDisciplina.length) {
            const alunos = alunosDisciplina.map(aluno => {
                return {
                    Matricula: aluno.matricula,
                    Id: aluno.id,
                    Nome: aluno.nome
                }
            });
            Grid_AlunosDisciplina.addRange(alunos);
        }
    }
}

async function aoAdicionarAlunoDisciplina(ev) {
    ev.preventDefault();
    const alunoEncontrado = Grid_AlunosDisciplina.getData().find(aluno => aluno.Id == Pesquisa_Aluno.obtenhaSelecionado().Id)

    if (alunoEncontrado) {
        new Modal().atencao("O aluno selecionado já encontra-se matriculado na disciplina").render();
        return;
    }

    const options = {
        url: `${APIHelper.LocalHostDisciplina}/student-classes`,
        data: {
            classID: idDisciplina,
            studentID: Pesquisa_Aluno.obtenhaSelecionado().Id
        }
    }

    const resposta = await postJSON(options);
    if (resposta) {
        const alunoSelecionado = {...Pesquisa_Aluno.obtenhaSelecionado(), selected: false}
        Grid_AlunosDisciplina.add(alunoSelecionado);
        new Modal().sucesso("Aluno incluído na disciplina com sucesso").render();
        Pesquisa_Aluno.limpe();
    }
}

function aoRemoverAlunoDisciplina(row) {
    new Modal().confirmacao("Tem certeza que deseja remover o aluno da disciplina ?", (ev) => {
        ev.preventDefault();
        aoConfirmarRemocaoAlunoDisciplina(row);
    }).render();
}

async function aoConfirmarRemocaoAlunoDisciplina(row) {
    const options = {
        url: `${APIHelper.LocalHostDisciplina}/student-classes`,
        data: {
            classID: idDisciplina,
            studentID: row.Id
        },
        method: "DELETE"
    }

    const resposta = await postJSON(options);
    if (resposta) {
        Grid_AlunosDisciplina.remove(row);
        new Modal().sucesso("Aluno removido da disciplina").render();
    }
}
</script>

DS.WEB/Pages/Disciplina/Aterrissagem.cshtml
@page
@model DS.WEB.Pages.Disciplina.AterrissagemDisciplinaModel
@{
    Layout = "_LayoutAterrissagem";
    ViewData["tituloFuncao"] = "Disciplinas";
}
<div class="row">
    <div class="col-xl-12">
        <vc:grid options="@(Html.GridOptions(m => m.Disciplinas)
                                .AddColumn(c => c.Bound(m => m.Nome))
                                .AddColumn(c => c.Bound(m => m.Horario))
                                .AddColumn(c => c.Bound(m => m.CargaHoraria).FlexBasis(300))
                                .AddAction(a => a.Remover().AoClicar("aoRemoverDisciplina"))
                                .AddAction(a => a.Editar().AoClicar("aoEditarDisciplina"))
                                .AddAction(a => a.AdicionarAluno().AoClicar("adicionarAlunoDisciplina")))"></vc:grid>
    </div>
</div>

<script defer>
EventDomContentLoaded(async () => {
    await pesquiseDisciplina();

    const botaoCadastrar = document.getElementById('cadastrar');
    botaoCadastrar.addEventListener('click', (ev) => {
        ev.preventDefault();
        window.location.href = '/Disciplina/Cadastrar';
    })
})

async function pesquiseDisciplina() {
    const optionsFetch = {
        url: `${APIHelper.LocalHostDisciplina}/classes`,
        method: "GET"
    }
    const resposta = await postJSON(optionsFetch);
    if (resposta) {
        const disciplinas = resposta.map(disciplina => {
            return {
                Nome: disciplina.name,
                Id: disciplina.id,
                Horario: disciplina.schedules,
                CargaHoraria: disciplina.total_hours + " hrs"
            }
        });
            Grid_Disciplinas.addRange(disciplinas);
    }
}

    function adicionarAlunoDisciplina(row) {
        window.location.href = `/Disciplina/AdicionarAlunoDisciplina?id=${row.Id}&nome=${row.Nome}`
    }

    function aoEditarDisciplina(row)
    {
        window.location.href = `/Disciplina/Cadastrar?id=${row.Id}`
    }

    function aoRemoverDisciplina(row){
        new Modal().confirmacao('Tem certeza que deseja excluir a disciplina selecionada ?', () => {
            aoConfirmarRemocaoDisciplina(row);
        }).render();

    }

    async function aoConfirmarRemocaoDisciplina(row){
        const options = {
            url: `${APIHelper.LocalHostDisciplina}/classes/${row.Id}`,
            method: "DELETE"
        }
        const resposta = await postJSON(options);

        if (resposta) {
            Grid_Disciplinas.remove(row);
            new Modal().sucesso('Disciplina excluida com sucesso').render();
        }
    }

</script>

DS.WEB/Pages/Disciplina/Cadastrar.cshtml
@page
@model DS.WEB.Pages.Disciplina.CadastrarDisciplinaModel
@{
    Layout = "_LayoutCadastro";
    ViewData["tituloFuncao"] = "Cadastro de disciplina";
    var idDisciplina = (string)ViewData["idDisciplina"];
}

<div class="row">
    <div class="col-xl-4">
        <label for="Nome" class="d-flex form-label">Nome</label>
        <div class="form-group" data="">
            <div class="input-group" data-target-input="nearest">
                <input type="text" id="Nome" name="Nome" class="form-control" value="" autocomplete="off">
            </div>
        </div>
    </div>

    <div class="col-xl-4">
        <label for="Descricao" class="d-flex form-label">Descrição</label>
        <div class="form-group" data="">
            <div class="input-group" data-target-input="nearest">
                <input type="text" id="Descricao" name="Descricao" class="form-control" value="" autocomplete="off">
            </div>
        </div>
    </div>

    <div class="col-xl-4">
        <vc:pesquisa options="@Html.Pesquisa(m => m.Professor).Action("http://localhost:5187/Professor", "GET")"></vc:pesquisa>
    </div>
</div>

<div class="row">
    <div class="col-xl-4">
        <label for="CargaHoraria" class="d-flex form-label">Carga horaria</label>
        <div class="form-group" data="">
            <div class="input-group" data-target-input="nearest">
                <input type="text" id="CargaHoraria" name="CargaHoraria" class="form-control" value="" autocomplete="off">
            </div>
        </div>
    </div>

    <div class="col-xl-4">
        <label for="HorarioDisciplina" class="d-flex form-label">Horário da disciplina</label>
        <div class="form-group" data="">
            <div class="input-group" data-target-input="nearest">
                <input type="text" id="HorarioDisciplina" name="HorarioDisciplina" class="form-control" value="" autocomplete="off">
            </div>
        </div>
    </div>
</div>

<script defer>
    EventDomContentLoaded(() => {
        const botaoGravar = document.getElementById('gravar');
        const botaoCancelar = document.getElementById('cancelar');
        botaoGravar.addEventListener('click', graveCadastroDisciplina)
        botaoCancelar.addEventListener('click', (ev) => {
            ev.preventDefault();
            new Modal().confirmacao("Tem certeza que deseja cancelar o cadastro?", () =>{
                window.location.href = '/Disciplina/Aterrissagem';
            }).render();
            
        });
        verifiqueEdicao();
    });

async function graveCadastroDisciplina(ev) {
    ev.preventDefault();
    const optionsFetch = {
        url: `${APIHelper.LocalHostDisciplina}/classes`,
        data: {
            description: Descricao.value,
            name: Nome.value,
            schedules: HorarioDisciplina.value,
            teacher_id: Pesquisa_Professor.obtenhaSelecionado().Id,
            total_hours: parseInt(CargaHoraria.value)
        }
        
    }
        console.log(idDisciplina != '');
   
        if (idDisciplina != '') {
            optionsFetch.method = "PUT"
            optionsFetch.url = `${APIHelper.LocalHostDisciplina}/classes/${idDisciplina}`;
            
        }
        const resposta = await postJSON(optionsFetch);
        if (resposta) {
            new Modal().sucesso(idDisciplina ? 'Disciplina editada com sucesso.' : 'Disciplina cadastrado com sucesso.').depoisDeOcultar(() => {
                window.location.href = '/Disciplina/Aterrissagem';
            }).render()
        }
}

    let idDisciplina;
    async function verifiqueEdicao() {
        const professores = await Pesquisa_Professor._filtre();

        idDisciplina = '@Html.Raw(idDisciplina)';
        if (idDisciplina) {
            var url = new URL(`${APIHelper.LocalHostDisciplina}/classes/${idDisciplina}`)
            const options = {
                url: url,
                method: "GET"
            }
            const resposta = await postJSON(options);
            if (resposta) {
                CargaHoraria.value = resposta.total_hours;
                Nome.value =  resposta.name;
                HorarioDisciplina.value = resposta.schedules;
                Descricao.value = resposta.description;

                if (professores.data) {
                    const professorSelecionado = professores.data.find(professor => professor.id == resposta.teacher_id);
                    if (professorSelecionado) {
                        Pesquisa_Professor.definaSelecionado(professorSelecionado);
                    }
                }
            }
        }
    }

</script>